#!/bin/bash

mkdir -p logs
virtualenv -p $(which python) .
source ./bin/activate

pip install -r requirements.txt

# An error like this on OS X is related to XCode:
# InstallationError: Command ... "import setuptools, tokenize;__file__= 
#    ... --single-version-externally-managed --compile failed with error code 1 in ...
# Try 'xcode-select --install' (or download/update command-like tools). 
# If that fails, uncomment the below and comment the other pip command:

# ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future \
#     pip install -r requirements.txt
