#!bin/python

import logging
import os
import sys

from lockfile.pidlockfile import PIDLockFile
from goosepaper import routed_app
from werkzeug.serving import run_simple
from settings import *

# Run flask or gunicorn depending on options
# Default is gunicorn
if len(sys.argv) == 2 and sys.argv[1] == "flask":
    print "Starting development server"
    run_simple(HOST, PORT, routed_app, use_reloader=True, use_debugger=DEBUG)
else:
    print "Starting gunicorn master with %d workers" % NUMBER_OF_WORKERS
    os.system("""gunicorn goosepaper:app \
                          --workers %d \
                          --bind 0.0.0.0:%d \
                          --daemon \
                          --access-logfile ./logs/access_log \
                          --error-log ./logs/error_log \
                          --pid ./daemon.pid""" % (NUMBER_OF_WORKERS, PORT))
    print "Done"

