#!/bin/bash

if [[ ! -e ./daemon.pid ]]; then
    echo -e "! Couldn't find PID file. Sure the daemon's running?"
    exit
fi

DAEMON_PID=$(cat ./daemon.pid)
echo -ne "Stopping master with PID $DAEMON_PID "
kill -9 $DAEMON_PID
rm ./daemon.pid
pkill -9 goosepaper:app

PROCS=$(($(ps aux | grep goosepaper:app  | wc -l) - 1))
while [ $PROCS -ne 0 ]; do
	PROCS=$(($(ps aux | grep goosepaper:app  | wc -l) - 1))
	echo -n "."
	sleep 1
done

echo -ne " done\n"
